# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
install:
  - bundle install
  - pod install
script:
  - bundle exec fastlane scan -w Example/HRSCustomErrorHandling.xcworkspace 
