# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
install:
  - bundle install
  - cd Example/ && pod install && cd -
script:
  - bundle exec fastlane scan -w Example/HRSCustomErrorHandling.xcworkspace 
